---
# handlers file for OpenVPN
- name: Restart OpenVPN.
  ansible.builtin.service:
    name: "openvpn@server"
    state: restarted

- name: Reload systemd.
  ansible.builtin.systemd_service:
    daemon_reload: true
