- name: Create config for CloudFront function.
  ansible.builtin.template:
    src: config.j2
    dest: cf_config
    owner: controller
    group: controller
    mode: 0644
  when: _funct.type == cf

- name: Create CF function.
  ansible.builtin.command:
    cmd: "aws cloudfront create-function --function-config file://cf_config --name new-funct --profile dummy --function-code fileb://{{ _ce_provision_build_dir }}/vars/_global/files/{{ _funct.code }}"
  when: _funct.type == cf
  register: _cf_function

- name: Setting previous command output into variable.
  ansible.builtin.set_fact:
    _cf_function: "{{ _cf_function.stdout | from_json }}"
  when: _funct.type == cf

- name: Register aws_lambda results.
  ansible.builtin.set_fact:
    _function_results: "{{ _function_results + [_cf_function] }}"
  when: _funct.type == cf
