- name: Configure vars if looping over list.
  ansible.builtin.set_fact:
    aws_vpc_sg:
      name: "{{ _sec_group.name | default('') }}"
      tags: "{{ _aws_vpc_vpc.vpc.tags | combine({'Name': _sec_group.name}) }}"
      id: "{{ _aws_vpc_vpc.vpc.id }}"
      description: "{{ _sec_group.description }}"
      rules: "{{ _sec_group.rules | default(omit) }}"
      rules_egress: "{{ _sec_group.rules_egress | default(omit) }}"
  when: _sec_group is defined

- name: Create Security Group.
  amazon.aws.ec2_security_group:
    name: "{{ aws_vpc_sg.name }}"
    profile: "{{ aws_vpc_sg.aws_profile | default(_aws_profile) }}"
    region: "{{ aws_vpc_sg.region | default(_aws_profile) }}"
    tags: "{{ aws_vpc_sg.tags | default({}) }}"
    state: "{{ aws_vpc_sg.state | default('present') }}"
    vpc_id: "{{ aws_vpc_sg.id }}"
    description: "{{ aws_vpc_sg.description | default('') }}"
    rules: "{{ aws_vpc_sg.rules | default(omit) }}"
    rules_egress: "{{ aws_vpc_sg.rules_egress | default(omit) }}"
    purge_rules: "{{ aws_vpc_sg.purge_rules | default(omit) }}"
  register: _aws_vpc_result

- name: Register aws_vpc SG results.
  ansible.builtin.set_fact:
    aws_vpc_sg: "{{ aws_vpc_sg | combine({'_result': {aws_vpc_sg.name: _aws_vpc_result}}, recursive=True) }}"
