---
before_script:
  - export $BASH_VARS

stages:
  - linting

ansible-lint:
  stage: linting
  image: registry.gitlab.com/pipeline-components/ansible-lint:latest
  script:
    - ansible-lint --show-relpath roles
