ce-provision-2.x:
  src: https://github.com/codeenigma/ce-provision.git
  src_branch: 2.x
  src_subdir: 'docs'
  dest: https://github.com/codeenigma/ce-provision-docs.git # remote and token for pushing added in GitHub Actions directly
  dest_branch: master
  dest_subdir: 2.x
  title: ce-provision
  type: doc
  base_url: https://codeenigma.github.io/ce-provision-docs/2.x
