---
- name: Ensure mysql is installed.
  ansible.builtin.apt:
    pkg: "mariadb-server"
    state: present
    update_cache: true

- name: Copy MySQL overriding configuration in place.
  ansible.builtin.template:
    src: zz_custom.cnf.j2
    dest: "/etc/mysql/conf.d/zz_custom.cnf"
    owner: root
    group: root
    mode: "0644"

- name: Ensure mysql can write data.
  ansible.builtin.file:
    path: /var/lib/mysql
    owner: mysql
    group: mysql
    recurse: true

- name: Ensure mysql can write PID/lock.
  ansible.builtin.file:
    path: /var/run/mysqld
    owner: mysql
    group: mysql
    mode: "0777"
    recurse: true

- name: Workaround Docker overlayFS issue.
  ansible.builtin.shell: >
    find /var/lib/mysql -type f -exec touch {} \;

- name: Restart mysql.
  ansible.builtin.service:
    name: mysql
    state: restarted
    enabled: true
