- name: Clone git repo.
  ansible.builtin.git:
    repo: "{{ aws_lambda.function_file }}"
    dest: /tmp/funct

- name: Copy a zip archive of Lambda function.
  community.general.archive:
    path: "/tmp/funct"
    dest: "{{ _ce_provision_build_dir }}/{{ aws_lambda.name }}.zip"
    format: zi
  when: string_type == 'url'
