- name: Create S3 bucket for Lambda functions.
  ansible.builtin.include_role:
    name: aws/aws_s3_bucket
  vars:
    aws_s3_bucket:
      profile: "{{ _aws_profile }}"
      region: "{{ _aws_region }}"
      name: "{{ aws_lambda.s3_bucket }}"
      tags: []
      state: "present"

- name: Check string type using regex
  ansible.builtin.set_fact:
    string_type: >-
      {%- if input_string | regex_search('^https?://') -%}
        url
      {%- elif input_string | regex_search('\.zip$', ignorecase=True) -%}
        zip
      {%- else -%}
        single
      {%- endif -%}
  vars:
    input_string: "{{ aws_lambda.function_file }}"

- name: Check and clean previous Lambda function.
  ansible.builtin.file:
    path: "{{ _ce_provision_build_dir }}/{{ aws_lambda.name }}.py"
    state: absent
  when: string_type == 'single'

- name: Write Lambda function.
  ansible.builtin.copy:
    content: "{{ aws_lambda.function_file }}"
    dest: "{{ _ce_provision_build_dir }}/{{ aws_lambda.name }}.py"
  when: string_type == 'single'

- name: Create a zip archive of Lambda function.
  community.general.archive:
    path: "{{ _ce_provision_build_dir }}/{{ aws_lambda.name }}.py"
    dest: "{{ _ce_provision_build_dir }}/{{ aws_lambda.name }}.zip"
    format: zip
  when: string_type == 'single'

- name: Copy a zip archive of Lambda function.
  ansible.builtin.copy:
    src: "{{ aws_lambda.function_file }}"
    dest: "{{ _ce_provision_build_dir }}/{{ aws_lambda.name }}.zip"
    owner: controller
    group: controller
    mode: '0644'
  when: string_type == 'zip'

- name: Place Lambda function in S3 bucket.
  amazon.aws.s3_object:
    bucket: "{{ aws_lambda.s3_bucket }}"
    object: "{{ aws_lambda.s3_bucket_prefix }}/{{ aws_lambda.name }}.zip"
    src: "{{ _ce_provision_build_dir }}/{{ aws_lambda.name }}.zip"
    mode: put

- name: Create Lambda function.
  amazon.aws.lambda:
    name: "{{ aws_lambda.name }}"
    description: "{{ aws_lambda.description }}"
    region: "{{ aws_lambda.region }}"
    timeout: "{{ aws_lambda.timeout }}"
    s3_bucket: "{{ aws_lambda.s3_bucket }}"
    s3_key: "{{ aws_lambda.s3_bucket_prefix }}/{{ aws_lambda.name }}.zip"
    state: present
    runtime: "{{ aws_lambda.runtime }}"
    role: "{{ aws_lambda.role.iam_role.arn }}"
    handler: "{{ aws_lambda.name }}.{{ aws_lambda.handler }}"
    tags: "{{ aws_lambda.tags }}"
  register: _aws_lambda_result

- name: Register aws_lambda results.
  ansible.builtin.set_fact:
    aws_lambda: "{{ aws_lambda | combine({'_result': {aws_lambda.name: _aws_lambda_result}}, recursive=True) }}"
