---
- name: Initialise virtual.
  ansible.builtin.command: /usr/sbin/postmap /etc/postfix/virtual

- name: Reload Postfix configuration.
  ansible.builtin.service:
    name: postfix
    state: reloaded
