---
# Default variables for YACE Exporter role
yace_exporter_version: "0.62.1"  # Adjust as needed
# Construct the download URL using the version variable.
yace_exporter_download_url: "https://github.com/prometheus-community/yet-another-cloudwatch-exporter/releases/download/v{{ yace_exporter_version }}/yet-another-cloudwatch-exporter-{{ yace_exporter_version }}.linux-amd64.tar.gz"

# Directories and file locations
yace_exporter_install_dir: "/usr/local/bin"
yace_exporter_system_user: "yace-exporter"
yace_exporter_system_group: "yace-exporter"
# Service runtime options
yace_exporter_listen_address: "0.0.0.0:9105"
yace_exporter_service_name: "yace_exporter"

# YACE configuration
yace_exporter_configuration: {}
#  apiVersion: v1alpha1
#  discovery:
#    jobs:
#      - type: AWS/EC2
#        regions:
#          - eu-west-1
#        metrics:
#          - name: CPUUtilization
#            statistics:
#              - Average
#            period: 300
#            length: 300
#      - type: AWS/RDS
#        regions:
#          - eu-west-1
#        searchTags:
#          - key: Ansible
#            value: managed
#        metrics:
#          - name: CPUUtilization
#            statistics:
#              - Average
#            period: 300
#            length: 300
#          - name: DatabaseConnections
#            statistics:
#              - Average
#              - Sum
#            period: 300
#            length: 300
#        dimensionNameRequirements:
#          - DBInstanceIdentifier

 # Server IAM policy to allow YACE service to pull metrics
yace_exporter_iam_configuration: |
  {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Action": [
                  "tag:GetResources",
                  "cloudwatch:GetMetricData",
                  "cloudwatch:GetMetricStatistics",
                  "cloudwatch:ListMetrics",
                  "ec2:DescribeSpotFleetRequests"
              ],
              "Effect": "Allow",
              "Resource": "*"
          }
      ]
  }
