---
- name: Ensure rkhunter is installed.
  ansible.builtin.apt:
    pkg: rkhunter
    state: present
    update_cache: true
    cache_valid_time: 240
  notify: Update rkhunter

- name: Check paths for script existence
  ansible.builtin.stat:
    path: "{{ item }}"
  register: _rkhunter_existing_scripts_to_whitelist
  loop: "{{ rkhunter.scriptwhitelist }}"
  when: rkhunter.scriptwhitelist | length > 0

- name: Filter existing scripts
  set_fact:
    existing_scripts: "{{ existing_scripts | default([]) + [item.item] }}"
  when:
    - item.stat.exists
    - _rkhunter_existing_scripts_to_whitelist is defined
  loop: "{{ _rkhunter_existing_scripts_to_whitelist.results }}"

- name: Check paths for portpath existence
  ansible.builtin.stat:
    path: "{{ item.split(':')[0] }}"
  register: _rkhunter_existing_portpaths_to_whitelist
  loop: "{{ rkhunter.portpathwhitelist }}"
  when: rkhunter.portpathwhitelist | length > 0

- name: Filter existing portpath
  set_fact:
    existing_portpaths: "{{ existing_portpaths | default([]) + [item.item] }}"
  when:
    - item.stat.exists
    - _rkhunter_existing_portpaths_to_whitelist is defined
  loop: "{{ _rkhunter_existing_portpaths_to_whitelist.results }}"

- name: Copy rkhunter configuration.
  ansible.builtin.template:
    src: rkhunter.conf.j2
    dest: /etc/rkhunter.conf
    owner: root
    group: root
    mode: 0644

- name: Copy rkhunter default startup configuration.
  ansible.builtin.template:
    src: rkhunter.default.j2
    dest: /etc/default/rkhunter
    owner: root
    group: root
    mode: 0644

- name: Trigger overrides
  ansible.builtin.include_role:
    name: _overrides
  vars:
    _overrides: "{{ rkhunter.overrides }}"
  when:
    - rkhunter.overrides is defined
    - rkhunter.overrides | length > 0
