---
- name: Ensure GPG is installed.
  ansible.builtin.apt:
    name: gpg
    state: present

- name: Generate GPG key.
  ansible.builtin.include_tasks: gpg.yml
  with_items: "{{ gpg_key }}"
  loop_control:
    loop_var: gpg_user
