aws_admin_tools:
  runtime: "python3.12"
  timeout: 20
  allowed_ips:
    - 192.168.1.1/32 # Ip of server with access to API-s
  functions:
    - name: "get_forecasted_costs"
      resource: api # can be "api" or "schedule"
      type: GET
      inline_policies: # Define inline policies which will be in use for executing Lambda function
        name: "{{ _aws_profile }}Billing"
        resource: "*"
        action:
          - "ce:*"
      policies: []
    - name: "change_asg_scaling"
      resource: api
      type: POST
      policies: []
      inline_policies:
        name: "change_asg_scaling"
        resource: "*"
        action:
          - "autoscaling:DescribePolicies"
          - "autoscaling:PutScalingPolicy"
    - name: "get_ip_set"
      resource: api
      type: GET
      url_params:
        - set_name
        - id
      policies: []
      inline_policies:
        name: "get_ip_set"
        resource: "*"
        action:
          - "wafv2:GetIPSet"
    - name: "test"
      resource: schedule
      cron: "cron(0 0 ? * MON *)" # If schedule is defined, we need the cron
      timeout: 300 # Timeout can be set per function, or use global if missing
      policies: []
      inline_policies:
        name: "test"
        resource: "*"
        action:
          - "wafv2:GetWebACL"
