---
aws_backup_validation:
  s3_bucket: "ce-{{ _aws_profile }}-lambda-functions"
  name: "RestoreValidation"
  description: "Restore validation is running every Sunday at 00:00AM, and validation reporting is triggered on Monday 00:00AM"
  timeout: 60
  runtime: "python3.12"
  handler: "lambda_handler"
  resources:
    - EC2
    - RDS
    #- EFS
