---
aws_backup_validation:
  s3_bucket: "{{ _general_bucket }}"
  s3_bucket_prefix: "backup-validation" # Prefix used for storing backup validation info
  description: "Restore validation is running every Sunday at 00:00AM, and validation reporting is triggered on Monday 00:00AM"
  timeout: 60
  runtime: "python3.12"
  main_file: "app"
  handler: "lambda_handler"
  git_url: example.git-url.codeenigma.com # Can be overwritten by git_url in item
  resources:
    - name: ec2_test_instance
      git: true # if true, it will build git url to download repo
      type: EC2
      lambda_policy:
        - "backup:PutRestoreValidationResult"
        - "ssm:GetCommandInvocation"
        - "ssm:GetConnectionStatus"
        - "ssm:SendCommand"
        - "ec2:DescribeInstances"
    - name: rds_test_instance
      git: true
      type:  RDS
      lambda_policy:
        - "backup:PutRestoreValidationResult"
        - "ssm:GetCommandInvocation"
        - "ssm:SendCommand"
        - "ec2:DescribeInstances"
        - "rds:DescribeDBInstances"
    - name: aurora_create_instance
      git: true
      type: Aurora
      lambda_policy:
        - "rds:DescribeDbClusters"
        - "rds:CreateDbInstance"
        - "rds:AddTagsToResource"
    - name: aurora_test_instance
      git: true
      type: Aurora
      event_pattern: '{ "source": ["aws.rds"], "detail-type": ["RDS DB Instance Event"], "resources": [{ "prefix": "arn:aws:rds:eu-west-1:{{ _acc_id }}:db:restoretest" }], "detail": { "EventID": ["RDS-EVENT-0005"] } }'
      lambda_policy:
        - "backup:PutRestoreValidationResult"
        - "ec2:DescribeInstances"
        - "rds:DescribeDBInstances"
        - "rds:DescribeDBClusters"
        - "rds:DeleteDBInstance"
    - name: validation_report
      git: true
      type: Schedule
      schedule: "cron(0 0 ? * MON *)"
      lambda_policy:
        - "backup:ListRestoreJobs"
        - "ses:SendEmail"
        - "ec2:DescribeImages"
        - "rds:DescribeDbSnapshots"
    #- EFS
