---
aws_backup_validation:
  function_location: gitlab.dummy-infra1.codeenigma.net
  s3_bucket: "{{ _general_bucket }}"
  s3_bucket_prefix: "backup-validation" # Prefix used for storing backup validation info
  name: "RestoreValidation"
  description: "Restore validation is running every Sunday at 00:00AM, and validation reporting is triggered on Monday 00:00AM"
  timeout: 60
  runtime: "python3.12"
  handler: "lambda_handler"
  resources:
    - name: ec2_test_instance
      git_url: ""
      type: EC2
      lambda_policy:
        - "backup:PutRestoreValidationResult"
        - "ssm:GetCommandInvocation"
        - "ssm:GetConnectionStatus"
        - "ssm:SendCommand"
        - "ec2:DescribeInstances"
    - name: rds_test_instance
      git_url: ""
      type: RDS
      lambda_policy:
        - "backup:PutRestoreValidationResult"
        - "ssm:GetCommandInvocation"
        - "ssm:SendCommand"
        - "ec2:DescribeInstances"
        - "rds:DescribeDBInstances"
    - name: aurora_create_instance
      git_url: ""
      type: Aurora
      lambda_policy:
        - "lambda:InvokeFunction"
    - name: aurora_test_instance
      git_url: ""
      type: Aurora
      event_pattern: '{ "source": ["aws.rds"], "detail-type": ["RDS DB Instance Event"], "resources": [{ "prefix": "arn:aws:rds:eu-west-1:{{ _acc_id }}:db:restoretest" }], "detail": { "EventID": ["RDS-EVENT-0005"] } }'
      lambda_policy:
        - "backup:PutRestoreValidationResult"
        - "ec2:DescribeInstances"
        - "rds:DescribeDBInstances"
        - "rds:DescribeDBClusters"
        - "rds:DeleteDBInstance"
    - name: validation_report
      git_url: ""
      type: Schedule 
      schedule: "cron(0 0 ? * MON *)"
      lambda_policy:
        - "backup:ListRestoreJobs"
        - "ses:SendEmail"
        - "ec2:DescribeImages"
        - "rds:DescribeDbSnapshots"
    #- EFS
