---
python_pip_packages:
  # These are usually set in the _init role but can be overridden here.
  venv_path: "{{ _venv_path }}"
  venv_command: "{{ _venv_command }}"
  venv_install_username: "{{ _venv_install_username }}"

  packages: []
  #  - name: pip
  #    state: latest
