---
collections:
  - name: community.mysql
  - name: community.sops
  - name: community.docker
  - name: community.aws
  - name: ansible.posix
  - name: amazon.aws
    version: "8.0.1" # ELB plugin broken since June
