- name: Create an IAM Managed Policy if defined.
  amazon.aws.iam_managed_policy:
    policy_name: "inline_{{ aws_iam_role.inline_policies.name }}_policy"
    policy:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Action: "{{ aws_iam_role.inline_policies.action }}"
          Resource: "{{ aws_iam_role.inline_policies.resource }}"
    state: present
  register: _inline_iam_policy
  when: aws_iam_role.inline_policies.action is defined and aws_iam_role.inline_policies.action | length > 0

- name: Join managed and inline policy.
  ansible.builtin.set_fact:
    _combined_policies: "{{ aws_iam_role.managed_policies + [_inline_iam_policy.policy.arn] }}"
  when: aws_iam_role.inline_policies.action is defined and aws_iam_role.inline_policies.action | length > 0

- name: Create combined var if inline policy is not defined or empty.
  ansible.builtin.set_fact:
    _combined_policies: "{{ aws_iam_role.managed_policies }}"
  when: aws_iam_role.inline_policies.action is not defined or aws_iam_role.inline_policies.action | length == 0

- name: Create list of strings for predefined policies.
  ansible.builtin.set_fact:
    allowed_strings: ["ec2", "ecs", "backup"]

- name: Create assume role policy document if predefined string is passed.
  ansible.builtin.set_fact:
    _assume_role_policy: "{{ lookup('file', aws_iam_role.policy_document + '_document_policy.json') }}"
  when: aws_iam_role.policy_document in allowed_strings

- name: Create assume role policy document if template is provided.
  ansible.builtin.set_fact:
    _assume_role_policy: "{{ aws_iam_role.policy_document }}"
  when: aws_iam_role.policy_document not in allowed_strings

- name: Create an IAM role.
  amazon.aws.iam_role:
    profile: "{{ aws_iam_role.aws_profile }}"
    name: "{{ aws_iam_role.name }}"
    assume_role_policy_document: "{{ _assume_role_policy }}"
    managed_policies: "{{ _combined_policies }}"
    purge_policies: "{{ aws_iam_role.purge_policies | default(true) }}"
    tags: "{{ aws_iam_role.tags | default({}) }}"
    create_instance_profile: "{% if aws_iam_role.policy_document == 'ec2' %}true{% else %}false{% endif %}"
    wait: true
  register: _aws_iam_role_result

- name: Wait for 6 seconds for IAM to be ready.
  ansible.builtin.wait_for:
    timeout: 6

- name: Register aws_iam_role results.
  ansible.builtin.set_fact:
    aws_iam_role: "{{ aws_iam_role | combine({'_result': {aws_iam_role.name: _aws_iam_role_result}}, recursive=True) }}"
