---
# This is the bare provisioning for the AMI.
- hosts: default
  become: true

  vars:
    _init:
      vars_dirs:
        - "{{ _ce_provision_build_dir }}/vars/_global"
        - "{{ _ce_provision_build_dir }}/vars/_regions/{{ _aws_region }}/_common"
        - "{{ _ce_provision_build_dir }}/vars/_regions/{{ _aws_region }}/{{ _env_type }}"
        - "{{ _ce_provision_build_dir }}/vars/{{ _aws_resource_name }}"

  tasks:
    - ansible.builtin.import_role:
        name: _init
    - ansible.builtin.import_role:
        name: debian/user_provision
    - ansible.builtin.import_role:
        name: _exit
