---
# First step. Spin up a "blank" instance from a fresh AMI.
- hosts: "_{{ _aws_resource_name | regex_replace('-', '_') }}"
  connection: local
  become: false

  vars:
    _init:
      vars_dirs:
        - "{{ _ce_provision_build_dir }}/vars/_global"
        - "{{ _ce_provision_build_dir }}/vars/_regions/{{ _aws_region }}/_common"
        - "{{ _ce_provision_build_dir }}/vars/_regions/{{ _aws_region }}/{{ _env_type }}"
        - "{{ _ce_provision_build_dir }}/vars/{{ _aws_resource_name }}"

  tasks:
    - ansible.builtin.import_role:
        name: _init
    - ansible.builtin.import_role:
        name: aws/aws_ec2_with_eip
    - ansible.builtin.import_role:
        name: _exit
    - ansible.builtin.meta: refresh_inventory
