---
- name: Install rsyslog with apt
  ansible.builtin.apt:
    name: rsyslog
    state: present
    update_cache: true

- name: Copy rsyslog configuration in place.
  ansible.builtin.template:
    src: "rsyslog.{{ rsyslog.role }}.conf.j2"
    dest: "/etc/rsyslog.conf"
    owner: root
    group: root
    mode: "0644"
    force: true

- name: Check if rsyslog init script exists
  ansible.builtin.stat:
    path: /etc/init.d/rsyslog
  register: rsyslog_init

- name: Restart rsyslog via init.d if available
  ansible.builtin.command: /etc/init.d/rsyslog restart
  when: rsyslog_init.stat.exists
  args:
    warn: false

- name: Restart rsyslog via service if init.d not available
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  when: not rsyslog_init.stat.exists
