---
- name: Install Java
  ansible.builtin.apt:
    name: openjdk-17-jre
    state: present
    update_cache: yes

- name: Install chromium and chromium-driver
  ansible.builtin.apt:
    name:
      - chromium
      - chromium-driver

- name: Create directory for Selenium Standalone
  ansible.builtin.file:
    path: /opt/selenium
    state: directory

- name: Download selenium-server-standalone.jar
  ansible.builtin.get_url:
    url: "https://github.com/SeleniumHQ/selenium/releases/download/selenium-{ selenium.version }/selenium-server-{ selenium.version }.jar"
    dest: /opt/selenium/selenium-server-standalone.jar
    mode: '0644'

- name: Create a script to run Selenium Standalone Server
  ansible.builtin.template:
    src: start-selenium.sh.j2
    dest: /opt/selenium/start-selenium.sh
    mode: '0755'

- name: Create a script to stop Selenium Standalone Server
  ansible.builtin.template:
    src: stop-selenium.sh.j2
    dest: /opt/selenium/stop-selenium.sh
    mode: '0755'

- name: Run Selenium Standalone Server in background
  ansible.builtin.shell: nohup /opt/selenium/start-selenium.sh &
  async: 30
  poll: 0

- name: Check if Selenium is running
  ansible.builtin.uri:
    url: "https://{ selenium.url_server }:{ selenium.port }{selenium.path}/status"
    return_content: yes
  register: result
  retries: 5
  delay: 10
  until: result.status == 200