---
- name: Fetch and extract Packer zip.
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/packer/{{ packer.version }}/packer_{{ packer.version }}_linux_amd64.zip
    dest: /usr/local/bin/
    remote_src: true
    mode: 0755

- name: Install the AWS EC2 plugin for Packer.
  command: "packer plugins install {{ item }}"
  with_items: "{{ packer.plugins }}"
  become: true
  become_user: "{{ ce_provision.username }}"
