---
# Bare provisioning of a new server.
# Use this command to execute:
#
#   cd /home/controller/ce-provision && \
#     ./scripts/provision.sh --workspace /home/controller/ce-provision \
#     --repo none --branch none \
#     --playbook /home/controller/ce-provision/plays/launcher/configure.yml \
#     --ansible-extra-vars "_provision_host=X.X.X.X"
#
# Replace X.X.X.X with your hostname or IP address.
- hosts: localhost
  vars:
    _ce_provision_username: controller
    _add_host: true # set to false if you do not want to add the new server to hosts.yml
    _ce_provision_config_branch: 2.x # change this if you didn't use our example config and have a different main branch name
  tasks:
    - name: Add the server to Ansible hosts in memory.
      ansible.builtin.add_host:
        hostname: "{{ _provision_host }}"

    - name: Add the server to hosts.yml.
      when: _add_host
      block:
      - name: Edit hosts.yml file.
        ansible.builtin.lineinfile:
          path: "/home/{{ _ce_provision_username }}/ce-provision/config/hosts/hosts.yml"
          line: "{{ _provision_host }}:"
          create: true

      - name: Add hosts.yml changes.
        ansible.builtin.command: git add .
        args:
          chdir: "/home/{{ _ce_provision_username }}/ce-provision/config"

      - name: Commit hosts.yml changes.
        ansible.builtin.shell: "git diff --staged --quiet || git commit -m 'Ansible autogenerated - host {{ _provision_host }} added.'"
        args:
          chdir: "/home/{{ _ce_provision_username }}/ce-provision/config"

      - name: Push the hosts file change to the config repository.
        ansible.builtin.command: "git push origin {{ _ce_provision_config_branch | default('main') }}"
        args:
          chdir: "/home/{{ _ce_provision_username }}/ce-provision/config"

- hosts: "{{ _provision_host }}"
  vars:
    ansible_user: admin
    _ce_provision_build_id: 0
  become: true
  tasks:
    - ansible.builtin.import_role:
        name: _init
    - ansible.builtin.import_role:
        name: debian/user_provision
    - ansible.builtin.import_role:
        name: _exit
