---
dependencies:
  - role: debian/user_provision
  - { role: debian/ssh_server, when: ( is_local is not defined or not is_local ) }
  - role: _meta/common_base
  - role: debian/ce_deploy
  - { role: aws/aws_credentials, when: ce_deploy.aws_support }
  - role: debian/gitlab
  - role: debian/gitlab_runner
  - role: debian/sops
  - role: debian/gpg_key
  - role: debian/user_deploy  # usually the deploy server's config repo is on the deploy server, so it needs to be able to deploy to itself.
