- name: Create stage on API gateway.
  ansible.builtin.command: >-
    aws apigateway create-stage
    --rest-api-id "{{ _api_gate.id }}"
    --stage-name "prod"
    --deployment-id "{{ _main_api_deploy.id }}"
    --region "{{ _aws_region }}"
  register: _main_api_stage
  when: _api_index | length == 0

- name: Create resources and set methods on API Gateway.
  ansible.builtin.include_tasks: create_methods.yml
  loop: "{{ aws_admin_tools.functions }}"

- name: Obtain all information for a single WAF.
  community.aws.wafv2_web_acl_info:
    name: "{{ _aws_profile }}_admin_tools"
    scope: "REGIONAL"
    region: "{{ _aws_region }}"
  register: _main_waf

- name: Get list of API gateway resources.
  ansible.builtin.command: >-
    aws apigateway get-resources
    --region "{{ _aws_region }}"
    --rest-api-id "{{ _api_gate.id }}"
  register: _api_res_list

- name: Setting previous command output into variable.
  ansible.builtin.set_fact:
    _api_res_list: "{{ _api_res_list.stdout | from_json | json_query('items') }}"

- name: Get index of DelMe resource from API gateway.
  ansible.builtin.set_fact:
    _api_res_index_list: "{{ lookup('ansible.utils.index_of', _api_res_list, 'eq', '/DelMe', 'path', wantlist=True) }}"
  when: _api_index | length == 0

- name: Delete the initial resource.
  ansible.builtin.command: >-
    aws apigateway delete-resource
    --rest-api-id "{{ _api_gate.id }}"
    --resource-id "{{ _api_res_list[_api_res_index_list[0]].id }}"
    --region "{{ _aws_region }}"
  when: _api_index | length == 0

- name: Deploy API gateway prior to attaching WAF.
  ansible.builtin.command: >-
    aws apigateway create-deployment
    --rest-api-id "{{ _api_gate.id }}"
    --stage-name "prod"
    --region "{{ _aws_region }}"

- name: Add API gateway to waf.
  community.aws.wafv2_resources:
    name: "{{ _aws_profile }}_admin_tools"
    scope: REGIONAL
    state: present
    region: "{{ _aws_region }}"
    arn: "arn:aws:apigateway:{{ _aws_region }}::/restapis/{{ _api_gate.id }}/stages/prod"

- name: Generate unique string.
  ansible.builtin.set_fact:
    _rand_str: "{{ lookup('community.general.random_string', length=8, special=false, min_lower=2, min_numeric=2, min_upper=2) }}"

- name: Update Lambda triggers.
  ansible.builtin.command: >-
    aws lambda add-permission
    --function-name "api_{{ item.name }}"
    --statement-id "{{ item.name }}_{{ _rand_str }}"
    --action "lambda:InvokeFunction"
    --principal apigateway.amazonaws.com
    --source-arn arn:aws:execute-api:{{ _aws_region }}:{{ _acc_id }}:{{ _api_gate.id }}/*/{{ item.type }}/{{ item.name }}
    --region {{ _aws_region }}
  loop: "{{ aws_admin_tools.functions }}"
