- name: Create schedule for validation reports.
  amazon.aws.cloudwatchevent_rule:
    name: "{{ item.name }}"
    schedule_expression: "{{ item.cron }}"
    description: "Scheduled function that generates info used by API Gateway."
    region: "{{ _aws_region }}"
    targets:
      - id: "{{ 'schedule_' + item.name }}"
        arn: "{{ (aws_lambda._result['schedule_' + item.name].configuration.function_arn.split(':') | map('trim'))[:-1] | join(':') }}" # Remove the version number from ARN
  register: _schedule_result

- name: Update Lambda policy.
  amazon.aws.lambda_policy:
    state: present
    function_name: "{{ 'schedule_' + item.name }}"
    statement_id: "{{ 'schedule_' + item.name }}"
    action: lambda:InvokeFunction
    principal: events.amazonaws.com
    source_arn: "{{ _schedule.rule.arn }}"
    region: "{{ _aws_region }}"
  loop: "{{ _schedule_result }}"
  loop_control:
    loop_var: _schedule
