- name: Create resource on API gateway.
  ansible.builtin.command: >-
    aws apigateway create-resource
    --rest-api-id "{{ _api_gate.id }}"
    --parent-id "{{ _api_res_list[_api_res_index_list[0]].id }}"
    --path-part "{{ item.name }}"
    --region "{{ _aws_region }}"
  register: _api_resource

- name: Setting previous command output into variable.
  ansible.builtin.set_fact:
    _api_resource: "{{ _api_resource.stdout | from_json }}"

- name: Put method on API gateway without URL params.
  ansible.builtin.command: >-
    aws apigateway put-method
    --rest-api-id "{{ _api_gate.id }}"
    --resource-id "{{ _api_resource.id }}"
    --http-method "{{ item.type }}"
    --authorization-type "NONE"
    --no-api-key-required
    --region "{{ _aws_region }}"
  when: item.url_params is not defined or item.url_params | length == 0

- name: Create request template string.
  ansible.builtin.template:
    src: request_template.j2
    dest: request_template
  when: item.url_params is defined and item.url_params | length > 0

- name: Put method on API gateway with URL params.
  ansible.builtin.command: >-
    aws apigateway put-method
    --rest-api-id "{{ _api_gate.id }}"
    --resource-id "{{ _api_resource.id }}"
    --http-method "{{ item.type }}"
    --authorization-type "NONE"
    --request-parameters file://request_template
    --no-api-key-required
    --region "{{ _aws_region }}"
  when: item.url_params is defined and item.url_params | length > 0

- name: Build arn for S3 bucket.
  ansible.builtin.set_fact:
    _target_arn: "arn:aws:apigateway:{{ _aws_region }}:s3:path/{{ item.bucket }}/{{ item.object }}"
  when: ite.resource == "s3"

- name: Build arn for Lambda.
  ansible.builtin.set_fact:
    _target_arn: "arn:aws:apigateway:{{ _aws_region }}:lambda:path/2015-03-31/functions/arn:aws:lambda:{{ _aws_region }}:{{ _acc_id }}:function:api_{{ item.name }}/invocations"
  when: ite.resource == "lambda"

- name: Add Lambda for method without URL params.
  ansible.builtin.command: >-
    aws apigateway put-integration
    --rest-api-id "{{ _api_gate.id }}"
    --resource-id "{{ _api_resource.id }}"
    --http-method "{{ item.type }}"
    --type AWS
    --content-handling CONVERT_TO_TEXT
    --integration-http-method POST
    --uri "{{ _target_arn }}"
    --region {{ _aws_region }}
  when: item.url_params is not defined or item.url_params | length == 0

- name: Generate template parts for each param
  set_fact:
    template_parts: "{{ item.url_params | map('regex_replace', '^(.*)$', '\\\"\\1\\\": \\\"$input.params(''\\1'')\\\"') | list }}"
  when: item.url_params is defined and item.url_params | length > 0

- name: Create final template string
  set_fact:
    template_string: "{ \"application/json\": \"{ {{ template_parts | join(',') }} }\" }"
  when: item.url_params is defined and item.url_params | length > 0

- name: Write template to file
  copy:
    content: "{{ template_string }}"
    dest: integration_template
  when: item.url_params is defined and item.url_params | length > 0

- name: Add Lambda for method with URL params.
  ansible.builtin.command: >-
    aws apigateway put-integration
    --rest-api-id "{{ _api_gate.id }}"
    --resource-id "{{ _api_resource.id }}"
    --http-method "{{ item.type }}"
    --type AWS
    --content-handling CONVERT_TO_TEXT
    --integration-http-method POST
    --passthrough-behavior WHEN_NO_TEMPLATES
    --request-template file://integration_template
    --uri "{{ _target_arn }}"
    --region {{ _aws_region }}
  when: item.url_params is defined and item.url_params | length > 0

- name: Add method response.
  ansible.builtin.command: >-
    aws apigateway put-method-response
    --rest-api-id "{{ _api_gate.id }}"
    --resource-id "{{ _api_resource.id }}"
    --http-method "{{ item.type }}"
    --status-code "200"
    --response-models '{"application/json":"Empty"}'
    --region {{ _aws_region }}

- name: Add integration response.
  ansible.builtin.command: >-
    aws apigateway put-integration-response
    --rest-api-id "{{ _api_gate.id }}"
    --resource-id "{{ _api_resource.id }}"
    --http-method "{{ item.type }}"
    --status-code "200"
    --selection-pattern ""
    --content-handling "CONVERT_TO_TEXT"
    --region {{ _aws_region }}
