- name: Create MOCK resource on API gateway.
  ansible.builtin.command: >-
    aws apigateway create-resource
    --rest-api-id "{{ _api_gate.id }}"
    --parent-id "{{ _api_res_list[_api_res_index_list[0]].id }}"
    --path-part "DelMe"
    --region "{{ _aws_region }}"
  register: _api_resource

- name: Setting command output into variable.
  ansible.builtin.set_fact:
    _api_resource: "{{ _api_resource.stdout | from_json }}"

- name: Put method on API gateway.
  ansible.builtin.command: >-
    aws apigateway put-method
    --rest-api-id "{{ _api_gate.id }}"
    --resource-id "{{ _api_resource.id }}"
    --http-method "GET"
    --authorization-type "NONE"
    --no-api-key-required
    --region "{{ _aws_region }}"

- name: Add mock integration.
  ansible.builtin.command: >-
    aws apigateway put-integration
    --rest-api-id "{{ _api_gate.id }}"
    --resource-id "{{ _api_resource.id }}"
    --http-method GET
    --type MOCK
    --region {{ _aws_region }}

- name: Create initial deployent for API gateway.
  ansible.builtin.command: >-
    aws apigateway create-deployment
    --rest-api-id "{{ _api_gate.id }}"
    --region "{{ _aws_region }}"
  register: _main_api_deploy

- name: Setting command output into variable.
  ansible.builtin.set_fact:
    _main_api_deploy: "{{ _main_api_deploy.stdout | from_json }}"
