- name: Get appropriate IAM role for Lambda.
  amazon.aws.iam_role_info:
    name: "{{ item.resource }}_{{ item.name }}"
  register: _iam_lambda

- name: Create Lambda function.
  ansible.builtin.include_role:
    name: aws/aws_lambda
  vars:
    aws_lambda:
      name: "{{ item.resource }}_{{ item.name }}"
      description: "Lambda function for {{ item.name }}"
      timeout: "{{ item.timeout | default(aws_admin_tools.timeout) }}"
      role: "{{ aws_iam_role._result[item.resource + '_' + item.name] }}"
      runtime: "{{ aws_admin_tools.runtime }}"
      function_file: "{{ lookup('template', item.resource + '_' + item.name + '.py.j2') }}"
      s3_bucket: "codeenigma-{{ _aws_profile }}-general-storage-{{ _aws_region }}"
      tags:
        Name: "{{ item.resource }}_{{ item.name }}"
