- name: List all for a specific function
  community.aws.api_gateway_info:
    region: "{{ _aws_region }}"
  register: _api_gateways

- name: Find the index of all firewalls using the type key
  ansible.builtin.set_fact:
    _admin_api_gateway: "{{ lookup('ansible.utils.index_of', _api_gateways['rest_apis'], 'eq', _aws_profile + '_admin_tools', 'name') }}"

- name: Find the index of all firewalls, use in a loop
  ansible.builtin.debug:
    msg: "{{ _api_gateways }}"

- name: Find the index of all firewalls, use in a loop
  ansible.builtin.debug:
    msg: "{{ _admin_api_gateway }}"

- name: Setup AWS API Gateway setup on AWS and deploy API definition
  community.aws.api_gateway:
    name: "{{ _aws_profile }}_admin_tools"
    region: "{{ _aws_region }}"
    swagger_text: "{{ lookup('template', 'swag.yml.j2') }}"
    stage: prod
    tracing_enabled: true
    endpoint_type: REGIONAL
    state: present

