- name: List all for a specific function
  community.aws.api_gateway_info:
    region: "{{ _aws_region }}"
  register: _api_gateways

- name: Find the index of admin tools API
  ansible.builtin.set_fact:
    _index_admin_api: "{{ lookup('ansible.utils.index_of', _api_gateways['rest_apis'], 'eq', _aws_profile + '_admin_tools', 'name', wantlist=True) }}"

- name: Get list of APIs
  debug:
    msg: "{{ _api_gateways }}"

- name: Setup AWS API Gateway setup on AWS and deploy API definition
  community.aws.api_gateway:
    name: "{{ _aws_profile }}_admin_tools"
    region: "{{ _aws_region }}"
    swagger_text: "{{ lookup('template', 'swag.yml.j2') }}"
    stage: prod
    tracing_enabled: true
    endpoint_type: REGIONAL
    state: present
  when: _index_admin_api | length == 0

- name: Update API definitions and settings and deploy as canary
  community.aws.api_gateway:
    api_id: "{{ _api_gateways['rest_apis'][_index_admin_api[0]]['id'] }}"
    name: "{{ _aws_profile }}_admin_tools"
    region: "{{ _aws_region }}"
    swagger_text: "{{ lookup('template', 'swag.yml.j2') }}"
    stage: prod
    tracing_enabled: true
    endpoint_type: REGIONAL
    state: present
  when: _index_admin_api | length > 0
