name: Publish docs

# Run this workflow on demand and every time a new commit pushed to your repository
on:
  pull_request:
  workflow_dispatch:

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  public-docs:
    if: ${{ github.event.pull_request.head.ref != 'documentation' }}
    # Name the Job
    name: Publish the ce-provision docs to GitHub
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    # Use our ce-dev Debian base container
    container:
      image: codeenigma/ce-dev-controller:2.x
      volumes:
        - ${{ github.workspace }}:/home/ce-dev/wiki2pages

    steps:
      - name: Install wiki2pages
        run: /usr/bin/su - ce-dev -c "/usr/bin/git clone https://github.com/codeenigma/wikis2pages.git /home/ce-dev/build/wiki2pages"

      - name: Set up Ansible hosts file
        run: |
          mkdir -p /home/ce-dev/ansible/bin/hosts
          echo "wikis2pages-hugo ansible_host=127.0.0.1" > /home/ce-dev/ansible/bin/hosts/hosts
          ls -la /home/ce-dev/
          echo "StrictHostKeyChecking=no" > /home/ce-dev/.ssh/config
          chown ce-dev:ce-dev /home/ce-dev/.ssh/config
          chmod 700 /home/ce-dev/.ssh/config

      - name: Start SSHD
        run: /usr/sbin/sshd&

      - name: Initialise wiki2pages for ce-provision 2.x
        run: |
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/build/wiki2pages && /bin/sh init.sh --repo https://github.com/codeenigma/ce-provision.git --branch 2.x --no-ce-dev"
          cat /home/ce-dev/ansible/bin/hosts/hosts
          cat /home/ce-dev/.ssh/config
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/build/wiki2pages && /home/ce-dev/ansible/bin/ansible-playbook -i /home/ce-dev/ansible/bin/hosts /home/ce-dev/build/wiki2pages/ce-dev/ansible/provision.yml"
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/build/wiki2pages && /bin/sh set-current.sh --project ce-provision-2.x --no-ce-dev"
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/build/wiki2pages && /home/ce-dev/ansible/bin/ansible-playbook -i /home/ce-dev/ansible/bin/hosts /home/ce-dev/build/wiki2pages/ce-dev/ansible/deploy.yml"
          ls -la public/
          ls -la public/ce-provision-2.x/
