name: Run web server test build

# Run this workflow every time a new commit pushed to your repository
on: pull_request

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test-web:
    # Name the Job
    name: Run tests against Ansible code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    # Use our ce-dev Debian base container
    container:
      image: codeenigma/ce-dev:2.x
      volumes:
        - ${{ github.workspace }}:/home/controller

    steps:
      - name: Install ce-provision
        if: ${{ github.event.pull_request.head.ref != 'documentation' }}
        run: |
          curl -LO https://raw.githubusercontent.com/codeenigma/ce-provision/${{ github.event.pull_request.head.ref }}/install.sh
          chmod +x ./install.sh
          sudo ./install.sh --version ${{ github.event.pull_request.head.ref }} --config-branch ${{ github.event.pull_request.base.ref }} --docker --no-firewall

      # Run a web server provision
      - name: Prepare Git repos on disk
        if: ${{ github.event.pull_request.head.ref != 'documentation' }}
        run: |
          git config --global --add safe.directory /home/controller/ce-provision
          git config --global --add safe.directory /home/controller/ce-provision/config

      - name: Provision a test web server
        if: ${{ github.event.pull_request.head.ref != 'documentation' }}
        run: |
          su - controller -c "cd /home/controller/ce-provision && /home/controller/ce-python/bin/ansible-galaxy role list"
          su - controller -c "cd /home/controller/ce-provision && /bin/sh /home/controller/ce-provision/scripts/provision.sh --python-interpreter /home/controller/ce-python/bin/python3 --repo dummy --branch dummy --workspace /home/controller/ce-provision/ce-dev/ansible --playbook plays/web/web.yml --own-branch ${{ github.event.pull_request.head.ref }} --config-branch ${{ github.event.pull_request.base.ref }} --force"
