name: Publish docs

# Run this workflow on demand or every time a PR is accepted to a main branch
on:
  pull_request:
    types: [closed]
    branches:
      - 1.x
      - 2.x
  workflow_dispatch:

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  public-docs:
    # Name the Job
    name: Publish the ce-provision docs to GitHub
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    # Use our ce-dev Debian base container
    container:
      image: codeenigma/ce-dev-controller:2.x
      volumes:
        - ${{ github.workspace }}:/home/controller

    steps:
      - uses: actions/checkout@v4
        with:
          ref: docs-${{ github.event.pull_request.base.ref }}

      # Configures global Git variables for committing
      - name: Configure Git
        run: |
          /usr/bin/git config --global user.email "sysadm@codeenigma.com"
          /usr/bin/git config --global user.name "Code Enigma CI"
          /usr/bin/git config --global pull.rebase false
          /usr/bin/git config --global --add safe.directory /__w/ce-provision/ce-provision

      # First build and publish the markdown docs
      - name: Build the table of contents
        run: /bin/sh contribute/toc.sh

      - name: Commit new table of contents back to the repo
        run: |
          /usr/bin/git add docs/.
          /usr/bin/git commit -m "GitHub Actions - updating markdown docs - ${{ steps.date.outputs.date }}"
          /usr/bin/git push

      # Create docs pull request
      - name: Create a documentation pull request
        if: ${{ github.event.pull_request.head.ref != 'docs-${{ github.event.pull_request.base.ref }}' }}
        run: gh pr create --base ${{ github.event.pull_request.base.ref }} --head docs-${{ github.event.pull_request.base.ref }} --title "**Automated pull request** created by GitHub Actions because of a documentation update."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Now build and publish the version of the docs
      - name: Install wiki2pages
        run: /usr/bin/su - ce-dev -c "/usr/bin/git clone https://github.com/codeenigma/wikis2pages.git /home/ce-dev/build/wiki2pages"

      - name: Update local applications
        run: |
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/ce-provision && /usr/bin/git pull origin 2.x"
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/ce-deploy && /usr/bin/git pull origin 1.x"

      - name: Set up Ansible hosts file
        run: |
          mkdir -p /home/ce-dev/ansible/bin/hosts
          echo "wikis2pages-hugo ansible_host=127.0.0.1" > /home/ce-dev/ansible/bin/hosts/hosts

      - name: Set up SSH config
        run: |
          echo "StrictHostKeyChecking=no" > /home/ce-dev/.ssh/config
          cat /home/ce-dev/.ssh/id_rsa.pub > /home/ce-dev/.ssh/authorized_keys
          chown ce-dev:ce-dev /home/ce-dev/.ssh/config
          chmod 700 /home/ce-dev/.ssh/config
          chown ce-dev:ce-dev /home/ce-dev/.ssh/authorized_keys
          chmod 700 /home/ce-dev/.ssh/authorized_keys

      - name: Start SSHD
        run: /usr/sbin/sshd&

      - name: Initialise wiki2pages for ce-provision ${{ github.event.pull_request.base.ref }}
        run: |
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/build/wiki2pages && /bin/sh init.sh --repo https://github.com/codeenigma/ce-provision.git --branch ${{ github.event.pull_request.base.ref }} --no-ce-dev"
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/build/wiki2pages && /home/ce-dev/ansible/bin/ansible-playbook -e 'wiki2pages_build_path=/home/ce-dev/build/wiki2pages' -i /home/ce-dev/ansible/bin/hosts /home/ce-dev/build/wiki2pages/ce-dev/ansible/provision.yml"
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/build/wiki2pages && /bin/sh set-current.sh --project ce-provision-${{ github.event.pull_request.base.ref }} --no-ce-dev"
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/build/wiki2pages && /home/ce-dev/ansible/bin/ansible-playbook -e 'wiki2pages_build_path=/home/ce-dev/build/wiki2pages launch_hugo_server=false' -i /home/ce-dev/ansible/bin/hosts /home/ce-dev/build/wiki2pages/ce-dev/ansible/deploy.yml"
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/build/wiki2pages/content/ce-provision-${{ github.event.pull_request.base.ref }} && /bin/sh contribute/toc_hugo.sh"

      - name: Run Hugo
        run: |
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/build/wiki2pages && hugo"
          ls -la /home/ce-dev/build/wiki2pages/public/ce-provision-${{ github.event.pull_request.base.ref }}/

      - name: Publish documentation
        run: |
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/build/wiki2pages && /bin/sh /home/ce-dev/build/wiki2pages/.github-actions-push.sh"
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/build/wiki2pages/public/ce-provision-${{ github.event.pull_request.base.ref }} && /usr/bin/git remote add ci https://${{ secrets.DOCS_GITHUB_TOKEN }}@github.com/codeenigma/ce-provision-docs.git"
          /usr/bin/su - ce-dev -c "cd /home/ce-dev/build/wiki2pages/public/ce-provision-${{ github.event.pull_request.base.ref }} && /usr/bin/git push ci master"
