aws_lambda:
  name: "lambda_function_name"
  description: "Description for AWS Lambda function"
  region: "{{ _aws_region }}"
  timeout: "20" # Maximum number of seconds before function times out
  handler: "lambda_handler" # Name of main function
  s3_bucket: "{{ _general_bucket }}"
  s3_bucket_prefix: "lambda-functions"
  function_file: "" # template to pass in S3 bucket
  runtime: "python3.12"
  role: ""
  tags: []
